language: python
python:
  - "3.4"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip coveralls
# command to run tests
script: 
  - python3 -m pytest --cov 
after_success:
  - coveralls
  - coverage report